Add asan to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -379,6 +379,85 @@ jobs:
           echo "::add-matcher::.github/problem-matchers/gcc.json"
           cat clang-tidy-ci-report.txt
           exit $(tail -n 1 clang-tidy-ci-report.txt | awk '{print $2}')
+  Lint-address-sanitizer:
+    needs: Formatting
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clone
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+      - name: Setup
+        run: |
+          echo "NPROCS=$(nproc)" >> $GITHUB_ENV
+          echo "CCACHE_COMPRESS=1" >> $GITHUB_ENV
+          echo "CCACHE_COMPRESSLEVEL=1" >> $GITHUB_ENV
+          echo "CCACHE_LOGFILE=${{github.workspace}}/ccache.log.txt" >> $GITHUB_ENV
+          echo "CCACHE_MAXSIZE=50M" >> $GITHUB_ENV
+          echo "CTCACHE_DIR=~/.cache/ctcache" >> $GITHUB_ENV
+      # - name: Install clang-tidy
+      #   run: |
+      #     echo 'Acquire::Retries "3";' | sudo tee /etc/apt/apt.conf.d/80-retries
+      #     if [[ ! -f /etc/apt/trusted.gpg.d/apt.llvm.org.asc ]]; then
+      #         wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
+      #     fi
+      #     source /etc/os-release # set UBUNTU_CODENAME
+      #     sudo add-apt-repository "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME} main"
+      #     sudo add-apt-repository "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${CLANG_TIDY_VERSION} main"
+      #     sudo apt-get update
+      #     sudo apt-get install -y --no-install-recommends clang-tidy-${CLANG_TIDY_VERSION} libomp-${CLANG_TIDY_VERSION}-dev
+      - name: Install Ccache
+        run: |
+          wget https://github.com/ccache/ccache/releases/download/v4.8/ccache-4.8-linux-x86_64.tar.xz
+          tar xvf ccache-4.8-linux-x86_64.tar.xz
+          sudo cp -f ccache-4.8-linux-x86_64/ccache /usr/local/bin/
+          mkdir -p ~/.cache/ctcache
+      - name: Set Up Ccache
+        uses: actions/cache@v4
+        with:
+          path: ~/.cache
+          key: ccache-${{github.workflow}}-${{github.job}}-git-${{github.sha}}
+          restore-keys: |
+               ccache-${{github.workflow}}-${{github.job}}-git-
+      - name: Configure
+        run: |
+          cmake \
+          -B ${{runner.workspace}}/build-ci-asan \
+          -DCMAKE_BUILD_TYPE:STRING=Release \
+          -DCMAKE_CXX_COMPILER:STRING=clang++ \
+          -DCMAKE_C_COMPILER:STRING=clang \
+          -DSPADES_ENABLE_MPI:BOOL=OFF \
+          -DSPADES_ENABLE_TESTS:BOOL=ON \
+          -DSPADES_TEST_WITH_FCOMPARE:BOOL=OFF \
+          -DSPADES_ENABLE_ALL_WARNINGS:BOOL=ON \
+          -DSPADES_ENABLE_SANITIZERS:BOOL=ON \
+          -DCMAKE_CXX_COMPILER_LAUNCHER:STRING=ccache \
+          ${{github.workspace}}
+      - name: Build
+        run: |
+          echo "::add-matcher::.github/problem-matchers/gcc.json"
+          ccache -z
+          set -eu -o pipefail
+          cmake --build ${{runner.workspace}}/build-ci-asan --parallel ${{env.NPROCS}} 2>&1 | \
+            tee -a ${{runner.workspace}}/build-ci-asan/build-output.txt
+      - name: Ccache Report
+        run: |
+          ccache -s
+          ls ~/.cache/ccache
+          du -hs ~/.cache/ccache
+      - name: Report
+        working-directory: ${{runner.workspace}}/build-ci-asan
+        run: |
+          echo "::add-matcher::.github/problem-matchers/gcc.json"
+          grep -E "warning:|error:" build-output.txt | grep -E -v "Submodules" \
+            | grep -E -v "ld: warning:" | grep -E -v "lto-wrapper: warning:" | sort | uniq \
+            | awk 'BEGIN{i=0}{print $0}{i++}END{print "Warnings: "i}' > build-output-warnings.txt
+          cat build-output-warnings.txt
+          exit $(tail -n 1 build-output-warnings.txt | awk '{print $2}')
+      - name: Test
+        working-directory: ${{runner.workspace}}/build-ci-asan
+        run: |
+          ctest --output-on-failure
   # Lint-codeql:
   #   needs: Formatting
   #   runs-on: ubuntu-latest
